// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FBS.Router
{

  using System;
  using System.Collections.Generic;
  using Google.FlatBuffers;
  using System.Text.Json.Serialization;

  public struct CreateWebRtcTransportRequest : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
    public static CreateWebRtcTransportRequest GetRootAsCreateWebRtcTransportRequest( ByteBuffer _bb ) { return GetRootAsCreateWebRtcTransportRequest( _bb, new CreateWebRtcTransportRequest() ); }
    public static CreateWebRtcTransportRequest GetRootAsCreateWebRtcTransportRequest( ByteBuffer _bb, CreateWebRtcTransportRequest obj ) { return (obj.__assign( _bb.GetInt( _bb.Position ) + _bb.Position, _bb )); }
    public void __init( int _i, ByteBuffer _bb ) { __p = new Table( _i, _bb ); }
    public CreateWebRtcTransportRequest __assign( int _i, ByteBuffer _bb ) { __init( _i, _bb ); return this; }

    public string TransportId { get { int o = __p.__offset( 4 ); return o != 0 ? __p.__string( o + __p.bb_pos ) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTransportIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
    public ArraySegment<byte>? GetTransportIdBytes() { return __p.__vector_as_arraysegment( 4 ); }
#endif
    public byte[] GetTransportIdArray() { return __p.__vector_as_array<byte>( 4 ); }
    public FBS.WebRtcTransport.WebRtcTransportOptions? Options { get { int o = __p.__offset( 6 ); return o != 0 ? ( FBS.WebRtcTransport.WebRtcTransportOptions? ) (new FBS.WebRtcTransport.WebRtcTransportOptions()).__assign( __p.__indirect( o + __p.bb_pos ), __p.bb ) : null; } }

    public static Offset<FBS.Router.CreateWebRtcTransportRequest> CreateCreateWebRtcTransportRequest( FlatBufferBuilder builder,
        StringOffset transport_idOffset = default( StringOffset ),
        Offset<FBS.WebRtcTransport.WebRtcTransportOptions> optionsOffset = default( Offset<FBS.WebRtcTransport.WebRtcTransportOptions> ) )
    {
      builder.StartTable( 2 );
      CreateWebRtcTransportRequest.AddOptions( builder, optionsOffset );
      CreateWebRtcTransportRequest.AddTransportId( builder, transport_idOffset );
      return CreateWebRtcTransportRequest.EndCreateWebRtcTransportRequest( builder );
    }

    public static void StartCreateWebRtcTransportRequest( FlatBufferBuilder builder ) { builder.StartTable( 2 ); }
    public static void AddTransportId( FlatBufferBuilder builder, StringOffset transportIdOffset ) { builder.AddOffset( 0, transportIdOffset.Value, 0 ); }
    public static void AddOptions( FlatBufferBuilder builder, Offset<FBS.WebRtcTransport.WebRtcTransportOptions> optionsOffset ) { builder.AddOffset( 1, optionsOffset.Value, 0 ); }
    public static Offset<FBS.Router.CreateWebRtcTransportRequest> EndCreateWebRtcTransportRequest( FlatBufferBuilder builder )
    {
      int o = builder.EndTable();
      builder.Required( o, 4 );  // transport_id
      builder.Required( o, 6 );  // options
      return new Offset<FBS.Router.CreateWebRtcTransportRequest>( o );
    }
    public CreateWebRtcTransportRequestT UnPack()
    {
      var _o = new CreateWebRtcTransportRequestT();
      this.UnPackTo( _o );
      return _o;
    }
    public void UnPackTo( CreateWebRtcTransportRequestT _o )
    {
      _o.TransportId = this.TransportId;
      _o.Options = this.Options.HasValue ? this.Options.Value.UnPack() : null;
    }
    public static Offset<FBS.Router.CreateWebRtcTransportRequest> Pack( FlatBufferBuilder builder, CreateWebRtcTransportRequestT _o )
    {
      if ( _o == null )
        return default( Offset<FBS.Router.CreateWebRtcTransportRequest> );
      var _transport_id = _o.TransportId == null ? default( StringOffset ) : builder.CreateString( _o.TransportId );
      var _options = _o.Options == null ? default( Offset<FBS.WebRtcTransport.WebRtcTransportOptions> ) : FBS.WebRtcTransport.WebRtcTransportOptions.Pack( builder, _o.Options );
      return CreateCreateWebRtcTransportRequest(
        builder,
        _transport_id,
        _options );
    }
  }

  public class CreateWebRtcTransportRequestT
  {
    [JsonPropertyName( "transport_id" )]
    public string TransportId { get; set; }
    [JsonPropertyName( "options" )]
    public FBS.WebRtcTransport.WebRtcTransportOptionsT Options { get; set; }

    public CreateWebRtcTransportRequestT()
    {
      this.TransportId = null;
      this.Options = null;
    }
  }


}
