// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;

namespace FBS.Router
{

    using global::System;
    using global::System.Collections.Generic;
    using global::Google.FlatBuffers;

    public struct CreateAudioLevelObserverRequest : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
        public static CreateAudioLevelObserverRequest GetRootAsCreateAudioLevelObserverRequest(ByteBuffer _bb) { return GetRootAsCreateAudioLevelObserverRequest(_bb, new CreateAudioLevelObserverRequest()); }
        public static CreateAudioLevelObserverRequest GetRootAsCreateAudioLevelObserverRequest(ByteBuffer _bb, CreateAudioLevelObserverRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public CreateAudioLevelObserverRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string RtpObserverId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRtpObserverIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetRtpObserverIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetRtpObserverIdArray() { return __p.__vector_as_array<byte>(4); }
        public FBS.AudioLevelObserver.AudioLevelObserverOptions? Options { get { int o = __p.__offset(6); return o != 0 ? (FBS.AudioLevelObserver.AudioLevelObserverOptions?)(new FBS.AudioLevelObserver.AudioLevelObserverOptions()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<FBS.Router.CreateAudioLevelObserverRequest> CreateCreateAudioLevelObserverRequest(FlatBufferBuilder builder,
            StringOffset rtp_observer_idOffset = default(StringOffset),
            Offset<FBS.AudioLevelObserver.AudioLevelObserverOptions> optionsOffset = default(Offset<FBS.AudioLevelObserver.AudioLevelObserverOptions>))
        {
            builder.StartTable(2);
            CreateAudioLevelObserverRequest.AddOptions(builder, optionsOffset);
            CreateAudioLevelObserverRequest.AddRtpObserverId(builder, rtp_observer_idOffset);
            return CreateAudioLevelObserverRequest.EndCreateAudioLevelObserverRequest(builder);
        }

        public static void StartCreateAudioLevelObserverRequest(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddRtpObserverId(FlatBufferBuilder builder, StringOffset rtpObserverIdOffset) { builder.AddOffset(0, rtpObserverIdOffset.Value, 0); }
        public static void AddOptions(FlatBufferBuilder builder, Offset<FBS.AudioLevelObserver.AudioLevelObserverOptions> optionsOffset) { builder.AddOffset(1, optionsOffset.Value, 0); }
        public static Offset<FBS.Router.CreateAudioLevelObserverRequest> EndCreateAudioLevelObserverRequest(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // rtp_observer_id
            builder.Required(o, 6);  // options
            return new Offset<FBS.Router.CreateAudioLevelObserverRequest>(o);
        }
        public CreateAudioLevelObserverRequestT UnPack()
        {
            var _o = new CreateAudioLevelObserverRequestT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(CreateAudioLevelObserverRequestT _o)
        {
            _o.RtpObserverId = this.RtpObserverId;
            _o.Options = this.Options.HasValue ? this.Options.Value.UnPack() : null;
        }
        public static Offset<FBS.Router.CreateAudioLevelObserverRequest> Pack(FlatBufferBuilder builder, CreateAudioLevelObserverRequestT _o)
        {
            if(_o == null)
                return default(Offset<FBS.Router.CreateAudioLevelObserverRequest>);
            var _rtp_observer_id = _o.RtpObserverId == null ? default(StringOffset) : builder.CreateString(_o.RtpObserverId);
            var _options = _o.Options == null ? default(Offset<FBS.AudioLevelObserver.AudioLevelObserverOptions>) : FBS.AudioLevelObserver.AudioLevelObserverOptions.Pack(builder, _o.Options);
            return CreateCreateAudioLevelObserverRequest(
              builder,
              _rtp_observer_id,
              _options);
        }
    }

    public class CreateAudioLevelObserverRequestT
    {
        public string RtpObserverId { get; set; }

        public FBS.AudioLevelObserver.AudioLevelObserverOptionsT Options { get; set; }

        public CreateAudioLevelObserverRequestT()
        {
            this.RtpObserverId = null;
            this.Options = null;
        }
    }


    static public class CreateAudioLevelObserverRequestVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*RtpObserverId*/, true)
              && verifier.VerifyTable(tablePos, 6 /*Options*/, FBS.AudioLevelObserver.AudioLevelObserverOptionsVerify.Verify, true)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
