// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FBS.Router
{

  using System;
  using System.Collections.Generic;
  using Google.FlatBuffers;
  using System.Text.Json.Serialization;

  public struct CreatePlainTransportRequest : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
    public static CreatePlainTransportRequest GetRootAsCreatePlainTransportRequest( ByteBuffer _bb ) { return GetRootAsCreatePlainTransportRequest( _bb, new CreatePlainTransportRequest() ); }
    public static CreatePlainTransportRequest GetRootAsCreatePlainTransportRequest( ByteBuffer _bb, CreatePlainTransportRequest obj ) { return (obj.__assign( _bb.GetInt( _bb.Position ) + _bb.Position, _bb )); }
    public void __init( int _i, ByteBuffer _bb ) { __p = new Table( _i, _bb ); }
    public CreatePlainTransportRequest __assign( int _i, ByteBuffer _bb ) { __init( _i, _bb ); return this; }

    public string TransportId { get { int o = __p.__offset( 4 ); return o != 0 ? __p.__string( o + __p.bb_pos ) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTransportIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
    public ArraySegment<byte>? GetTransportIdBytes() { return __p.__vector_as_arraysegment( 4 ); }
#endif
    public byte[] GetTransportIdArray() { return __p.__vector_as_array<byte>( 4 ); }
    public FBS.PlainTransport.PlainTransportOptions? Options { get { int o = __p.__offset( 6 ); return o != 0 ? ( FBS.PlainTransport.PlainTransportOptions? ) (new FBS.PlainTransport.PlainTransportOptions()).__assign( __p.__indirect( o + __p.bb_pos ), __p.bb ) : null; } }

    public static Offset<FBS.Router.CreatePlainTransportRequest> CreateCreatePlainTransportRequest( FlatBufferBuilder builder,
        StringOffset transport_idOffset = default( StringOffset ),
        Offset<FBS.PlainTransport.PlainTransportOptions> optionsOffset = default( Offset<FBS.PlainTransport.PlainTransportOptions> ) )
    {
      builder.StartTable( 2 );
      CreatePlainTransportRequest.AddOptions( builder, optionsOffset );
      CreatePlainTransportRequest.AddTransportId( builder, transport_idOffset );
      return CreatePlainTransportRequest.EndCreatePlainTransportRequest( builder );
    }

    public static void StartCreatePlainTransportRequest( FlatBufferBuilder builder ) { builder.StartTable( 2 ); }
    public static void AddTransportId( FlatBufferBuilder builder, StringOffset transportIdOffset ) { builder.AddOffset( 0, transportIdOffset.Value, 0 ); }
    public static void AddOptions( FlatBufferBuilder builder, Offset<FBS.PlainTransport.PlainTransportOptions> optionsOffset ) { builder.AddOffset( 1, optionsOffset.Value, 0 ); }
    public static Offset<FBS.Router.CreatePlainTransportRequest> EndCreatePlainTransportRequest( FlatBufferBuilder builder )
    {
      int o = builder.EndTable();
      builder.Required( o, 4 );  // transport_id
      builder.Required( o, 6 );  // options
      return new Offset<FBS.Router.CreatePlainTransportRequest>( o );
    }
    public CreatePlainTransportRequestT UnPack()
    {
      var _o = new CreatePlainTransportRequestT();
      this.UnPackTo( _o );
      return _o;
    }
    public void UnPackTo( CreatePlainTransportRequestT _o )
    {
      _o.TransportId = this.TransportId;
      _o.Options = this.Options.HasValue ? this.Options.Value.UnPack() : null;
    }
    public static Offset<FBS.Router.CreatePlainTransportRequest> Pack( FlatBufferBuilder builder, CreatePlainTransportRequestT _o )
    {
      if ( _o == null )
        return default( Offset<FBS.Router.CreatePlainTransportRequest> );
      var _transport_id = _o.TransportId == null ? default( StringOffset ) : builder.CreateString( _o.TransportId );
      var _options = _o.Options == null ? default( Offset<FBS.PlainTransport.PlainTransportOptions> ) : FBS.PlainTransport.PlainTransportOptions.Pack( builder, _o.Options );
      return CreateCreatePlainTransportRequest(
        builder,
        _transport_id,
        _options );
    }
  }

  public class CreatePlainTransportRequestT
  {
    [JsonPropertyName( "transport_id" )]
    public string TransportId { get; set; }
    [JsonPropertyName( "options" )]
    public FBS.PlainTransport.PlainTransportOptionsT Options { get; set; }

    public CreatePlainTransportRequestT()
    {
      this.TransportId = null;
      this.Options = null;
    }
  }


}
