// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using Google.FlatBuffers;
using System.Text.Json.Serialization;

namespace FBS.Transport
{
    public struct CloseConsumerRequest : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static CloseConsumerRequest GetRootAsCloseConsumerRequest(ByteBuffer _bb) { return GetRootAsCloseConsumerRequest(_bb, new CloseConsumerRequest()); }
        public static CloseConsumerRequest GetRootAsCloseConsumerRequest(ByteBuffer _bb, CloseConsumerRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public CloseConsumerRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string ConsumerId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetConsumerIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetConsumerIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetConsumerIdArray() { return __p.__vector_as_array<byte>(4); }

        public static Offset<FBS.Transport.CloseConsumerRequest> CreateCloseConsumerRequest(FlatBufferBuilder builder,
            StringOffset consumer_idOffset = default(StringOffset))
        {
            builder.StartTable(1);
            CloseConsumerRequest.AddConsumerId(builder, consumer_idOffset);
            return CloseConsumerRequest.EndCloseConsumerRequest(builder);
        }

        public static void StartCloseConsumerRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddConsumerId(FlatBufferBuilder builder, StringOffset consumerIdOffset) { builder.AddOffset(0, consumerIdOffset.Value, 0); }
        public static Offset<FBS.Transport.CloseConsumerRequest> EndCloseConsumerRequest(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // consumer_id
            return new Offset<FBS.Transport.CloseConsumerRequest>(o);
        }
        public CloseConsumerRequestT UnPack()
        {
            var _o = new CloseConsumerRequestT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(CloseConsumerRequestT _o)
        {
            _o.ConsumerId = this.ConsumerId;
        }
        public static Offset<FBS.Transport.CloseConsumerRequest> Pack(FlatBufferBuilder builder, CloseConsumerRequestT _o)
        {
            if(_o == null)
                return default(Offset<FBS.Transport.CloseConsumerRequest>);
            var _consumer_id = _o.ConsumerId == null ? default(StringOffset) : builder.CreateString(_o.ConsumerId);
            return CreateCloseConsumerRequest(
              builder,
              _consumer_id);
        }
    }

    public class CloseConsumerRequestT
    {
        [JsonPropertyName("consumer_id")]
        public string ConsumerId { get; set; }

        public CloseConsumerRequestT()
        {
            this.ConsumerId = null;
        }
    }
}
