// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;

namespace FBS.Transport
{

    using global::System;
    using global::System.Collections.Generic;
    using global::Google.FlatBuffers;

    public struct ProduceResponse : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
        public static ProduceResponse GetRootAsProduceResponse(ByteBuffer _bb) { return GetRootAsProduceResponse(_bb, new ProduceResponse()); }
        public static ProduceResponse GetRootAsProduceResponse(ByteBuffer _bb, ProduceResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public ProduceResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public FBS.RtpParameters.Type Type { get { int o = __p.__offset(4); return o != 0 ? (FBS.RtpParameters.Type)__p.bb.Get(o + __p.bb_pos) : FBS.RtpParameters.Type.SIMPLE; } }

        public static Offset<FBS.Transport.ProduceResponse> CreateProduceResponse(FlatBufferBuilder builder,
            FBS.RtpParameters.Type type = FBS.RtpParameters.Type.SIMPLE)
        {
            builder.StartTable(1);
            ProduceResponse.AddType(builder, type);
            return ProduceResponse.EndProduceResponse(builder);
        }

        public static void StartProduceResponse(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddType(FlatBufferBuilder builder, FBS.RtpParameters.Type type) { builder.AddByte(0, (byte)type, 0); }
        public static Offset<FBS.Transport.ProduceResponse> EndProduceResponse(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<FBS.Transport.ProduceResponse>(o);
        }
        public ProduceResponseT UnPack()
        {
            var _o = new ProduceResponseT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(ProduceResponseT _o)
        {
            _o.Type = this.Type;
        }
        public static Offset<FBS.Transport.ProduceResponse> Pack(FlatBufferBuilder builder, ProduceResponseT _o)
        {
            if(_o == null)
                return default(Offset<FBS.Transport.ProduceResponse>);
            return CreateProduceResponse(
              builder,
              _o.Type);
        }
    }

    public class ProduceResponseT
    {
        public FBS.RtpParameters.Type Type { get; set; }

        public ProduceResponseT()
        {
            this.Type = FBS.RtpParameters.Type.SIMPLE;
        }
    }


    static public class ProduceResponseVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyField(tablePos, 4 /*Type*/, 1 /*FBS.RtpParameters.Type*/, 1, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
