// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;

namespace FBS.Transport
{

    using global::System;
    using global::System.Collections.Generic;
    using global::Google.FlatBuffers;

    public struct SctpStateChangeNotification : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
        public static SctpStateChangeNotification GetRootAsSctpStateChangeNotification(ByteBuffer _bb) { return GetRootAsSctpStateChangeNotification(_bb, new SctpStateChangeNotification()); }
        public static SctpStateChangeNotification GetRootAsSctpStateChangeNotification(ByteBuffer _bb, SctpStateChangeNotification obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public SctpStateChangeNotification __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public FBS.SctpAssociation.SctpState SctpState { get { int o = __p.__offset(4); return o != 0 ? (FBS.SctpAssociation.SctpState)__p.bb.Get(o + __p.bb_pos) : FBS.SctpAssociation.SctpState.NEW; } }

        public static Offset<FBS.Transport.SctpStateChangeNotification> CreateSctpStateChangeNotification(FlatBufferBuilder builder,
            FBS.SctpAssociation.SctpState sctp_state = FBS.SctpAssociation.SctpState.NEW)
        {
            builder.StartTable(1);
            SctpStateChangeNotification.AddSctpState(builder, sctp_state);
            return SctpStateChangeNotification.EndSctpStateChangeNotification(builder);
        }

        public static void StartSctpStateChangeNotification(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddSctpState(FlatBufferBuilder builder, FBS.SctpAssociation.SctpState sctpState) { builder.AddByte(0, (byte)sctpState, 0); }
        public static Offset<FBS.Transport.SctpStateChangeNotification> EndSctpStateChangeNotification(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<FBS.Transport.SctpStateChangeNotification>(o);
        }
        public SctpStateChangeNotificationT UnPack()
        {
            var _o = new SctpStateChangeNotificationT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(SctpStateChangeNotificationT _o)
        {
            _o.SctpState = this.SctpState;
        }
        public static Offset<FBS.Transport.SctpStateChangeNotification> Pack(FlatBufferBuilder builder, SctpStateChangeNotificationT _o)
        {
            if(_o == null)
                return default(Offset<FBS.Transport.SctpStateChangeNotification>);
            return CreateSctpStateChangeNotification(
              builder,
              _o.SctpState);
        }
    }

    public class SctpStateChangeNotificationT
    {
        public FBS.SctpAssociation.SctpState SctpState { get; set; }

        public SctpStateChangeNotificationT()
        {
            this.SctpState = FBS.SctpAssociation.SctpState.NEW;
        }
    }


    static public class SctpStateChangeNotificationVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyField(tablePos, 4 /*SctpState*/, 1 /*FBS.SctpAssociation.SctpState*/, 1, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
