// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FBS.Transport
{
    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    public enum TraceInfo : byte
    {
        [EnumMember(Value = "none")]
        NONE = 0,

        [EnumMember(Value = "bweTraceInfo")]
        BweTraceInfo = 1,
    }

    public class TraceInfoUnion
    {
        public TraceInfo Type { get; set; }
        public object Value { get; set; }

        public TraceInfoUnion()
        {
            this.Type = TraceInfo.NONE;
            this.Value = null;
        }

        public T As<T>() where T : class { return this.Value as T; }
        public FBS.Transport.BweTraceInfoT AsBweTraceInfo() { return this.As<FBS.Transport.BweTraceInfoT>(); }
        public static TraceInfoUnion FromBweTraceInfo(FBS.Transport.BweTraceInfoT _bwetraceinfo) { return new TraceInfoUnion { Type = TraceInfo.BweTraceInfo, Value = _bwetraceinfo }; }

        public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, TraceInfoUnion _o)
        {
            switch(_o.Type)
            {
                default:
                    return 0;
                case TraceInfo.BweTraceInfo:
                    return FBS.Transport.BweTraceInfo.Pack(builder, _o.AsBweTraceInfo()).Value;
            }
        }
    }
}
