// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using Google.FlatBuffers;
using System.Text.Json.Serialization;

namespace FBS.RtpParameters
{
    public struct Boolean : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static Boolean GetRootAsBoolean(ByteBuffer _bb) { return GetRootAsBoolean(_bb, new Boolean()); }
        public static Boolean GetRootAsBoolean(ByteBuffer _bb, Boolean obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Boolean __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public byte Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

        public static Offset<FBS.RtpParameters.Boolean> CreateBoolean(FlatBufferBuilder builder,
            byte value = 0)
        {
            builder.StartTable(1);
            Boolean.AddValue(builder, value);
            return Boolean.EndBoolean(builder);
        }

        public static void StartBoolean(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddValue(FlatBufferBuilder builder, byte value) { builder.AddByte(0, value, 0); }
        public static Offset<FBS.RtpParameters.Boolean> EndBoolean(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<FBS.RtpParameters.Boolean>(o);
        }
        public BooleanT UnPack()
        {
            var _o = new BooleanT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(BooleanT _o)
        {
            _o.Value = this.Value;
        }
        public static Offset<FBS.RtpParameters.Boolean> Pack(FlatBufferBuilder builder, BooleanT _o)
        {
            if(_o == null)
                return default(Offset<FBS.RtpParameters.Boolean>);
            return CreateBoolean(
              builder,
              _o.Value);
        }
    }

    public class BooleanT
    {
        [JsonPropertyName("value")]
        public byte Value { get; set; }

        public BooleanT()
        {
            this.Value = 0;
        }
    }
}
