// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;

namespace FBS.RtpParameters
{

    using global::System;
    using global::System.Collections.Generic;
    using global::Google.FlatBuffers;

    public struct Integer32 : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
        public static Integer32 GetRootAsInteger32(ByteBuffer _bb) { return GetRootAsInteger32(_bb, new Integer32()); }
        public static Integer32 GetRootAsInteger32(ByteBuffer _bb, Integer32 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Integer32 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public int Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

        public static Offset<FBS.RtpParameters.Integer32> CreateInteger32(FlatBufferBuilder builder,
            int value = 0)
        {
            builder.StartTable(1);
            Integer32.AddValue(builder, value);
            return Integer32.EndInteger32(builder);
        }

        public static void StartInteger32(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddValue(FlatBufferBuilder builder, int value) { builder.AddInt(0, value, 0); }
        public static Offset<FBS.RtpParameters.Integer32> EndInteger32(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<FBS.RtpParameters.Integer32>(o);
        }
        public Integer32T UnPack()
        {
            var _o = new Integer32T();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(Integer32T _o)
        {
            _o.Value = this.Value;
        }
        public static Offset<FBS.RtpParameters.Integer32> Pack(FlatBufferBuilder builder, Integer32T _o)
        {
            if(_o == null)
                return default(Offset<FBS.RtpParameters.Integer32>);
            return CreateInteger32(
              builder,
              _o.Value);
        }
    }

    public class Integer32T
    {
        public int Value { get; set; }

        public Integer32T()
        {
            this.Value = 0;
        }
    }


    static public class Integer32Verify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyField(tablePos, 4 /*Value*/, 4 /*int*/, 4, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
