// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FBS.RtpParameters
{
    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    public enum MediaKind : byte
    {
        [EnumMember(Value = "audio")]
        AUDIO = 0,

        [EnumMember(Value = "video")]
        VIDEO = 1,
    }
}
