// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;

namespace FBS.WebRtcTransport
{

    using global::System;
    using global::System.Collections.Generic;
    using global::Google.FlatBuffers;

    public struct ConnectRequest : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
        public static ConnectRequest GetRootAsConnectRequest(ByteBuffer _bb) { return GetRootAsConnectRequest(_bb, new ConnectRequest()); }
        public static ConnectRequest GetRootAsConnectRequest(ByteBuffer _bb, ConnectRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public ConnectRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public FBS.WebRtcTransport.DtlsParameters? DtlsParameters { get { int o = __p.__offset(4); return o != 0 ? (FBS.WebRtcTransport.DtlsParameters?)(new FBS.WebRtcTransport.DtlsParameters()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<FBS.WebRtcTransport.ConnectRequest> CreateConnectRequest(FlatBufferBuilder builder,
            Offset<FBS.WebRtcTransport.DtlsParameters> dtls_parametersOffset = default(Offset<FBS.WebRtcTransport.DtlsParameters>))
        {
            builder.StartTable(1);
            ConnectRequest.AddDtlsParameters(builder, dtls_parametersOffset);
            return ConnectRequest.EndConnectRequest(builder);
        }

        public static void StartConnectRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddDtlsParameters(FlatBufferBuilder builder, Offset<FBS.WebRtcTransport.DtlsParameters> dtlsParametersOffset) { builder.AddOffset(0, dtlsParametersOffset.Value, 0); }
        public static Offset<FBS.WebRtcTransport.ConnectRequest> EndConnectRequest(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // dtls_parameters
            return new Offset<FBS.WebRtcTransport.ConnectRequest>(o);
        }
        public ConnectRequestT UnPack()
        {
            var _o = new ConnectRequestT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(ConnectRequestT _o)
        {
            _o.DtlsParameters = this.DtlsParameters.HasValue ? this.DtlsParameters.Value.UnPack() : null;
        }
        public static Offset<FBS.WebRtcTransport.ConnectRequest> Pack(FlatBufferBuilder builder, ConnectRequestT _o)
        {
            if(_o == null)
                return default(Offset<FBS.WebRtcTransport.ConnectRequest>);
            var _dtls_parameters = _o.DtlsParameters == null ? default(Offset<FBS.WebRtcTransport.DtlsParameters>) : FBS.WebRtcTransport.DtlsParameters.Pack(builder, _o.DtlsParameters);
            return CreateConnectRequest(
              builder,
              _dtls_parameters);
        }
    }

    public class ConnectRequestT
    {
        public FBS.WebRtcTransport.DtlsParametersT DtlsParameters { get; set; }

        public ConnectRequestT()
        {
            this.DtlsParameters = null;
        }
    }


    static public class ConnectRequestVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyTable(tablePos, 4 /*DtlsParameters*/, FBS.WebRtcTransport.DtlsParametersVerify.Verify, true)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
