// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FBS.WebRtcTransport
{
    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    public enum FingerprintAlgorithm : byte
    {
        [EnumMember(Value = "sha-1")]
        SHA1 = 0,

        [EnumMember(Value = "sha-224")]
        SHA224 = 1,

        [EnumMember(Value = "sha-256")]
        SHA256 = 2,

        [EnumMember(Value = "sha-384")]
        SHA384 = 3,

        [EnumMember(Value = "sha-512")]
        SHA512 = 4,
    }
}
