// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FBS.WebRtcTransport
{
    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    public enum IceCandidateType : byte
    {
        [EnumMember(Value = "host")]
        HOST = 0,
    }
}
