// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FBS.WebRtcTransport
{
    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    public enum IceState : byte
    {
        [EnumMember(Value = "new")]
        NEW = 0,

        [EnumMember(Value = "connected")]
        CONNECTED = 1,

        [EnumMember(Value = "completed")]
        COMPLETED = 2,

        [EnumMember(Value = "disconnected")]
        DISCONNECTED = 3,
    }
}
