// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FBS.PlainTransport
{
    using Google.FlatBuffers;
    using System.Text.Json.Serialization;

    public struct DumpResponse : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static DumpResponse GetRootAsDumpResponse(ByteBuffer _bb) { return GetRootAsDumpResponse(_bb, new DumpResponse()); }
        public static DumpResponse GetRootAsDumpResponse(ByteBuffer _bb, DumpResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public DumpResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public FBS.Transport.Dump? Base { get { int o = __p.__offset(4); return o != 0 ? (FBS.Transport.Dump?)(new FBS.Transport.Dump()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public bool RtcpMux { get { int o = __p.__offset(6); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }
        public bool Comedia { get { int o = __p.__offset(8); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }
        public FBS.Transport.Tuple? Tuple { get { int o = __p.__offset(10); return o != 0 ? (FBS.Transport.Tuple?)(new FBS.Transport.Tuple()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public FBS.Transport.Tuple? RtcpTuple { get { int o = __p.__offset(12); return o != 0 ? (FBS.Transport.Tuple?)(new FBS.Transport.Tuple()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public FBS.SrtpParameters.SrtpParameters? SrtpParameters { get { int o = __p.__offset(14); return o != 0 ? (FBS.SrtpParameters.SrtpParameters?)(new FBS.SrtpParameters.SrtpParameters()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<FBS.PlainTransport.DumpResponse> CreateDumpResponse(FlatBufferBuilder builder,
            Offset<FBS.Transport.Dump> @baseOffset = default(Offset<FBS.Transport.Dump>),
            bool rtcp_mux = false,
            bool comedia = false,
            Offset<FBS.Transport.Tuple> tupleOffset = default(Offset<FBS.Transport.Tuple>),
            Offset<FBS.Transport.Tuple> rtcp_tupleOffset = default(Offset<FBS.Transport.Tuple>),
            Offset<FBS.SrtpParameters.SrtpParameters> srtp_parametersOffset = default(Offset<FBS.SrtpParameters.SrtpParameters>))
        {
            builder.StartTable(6);
            DumpResponse.AddSrtpParameters(builder, srtp_parametersOffset);
            DumpResponse.AddRtcpTuple(builder, rtcp_tupleOffset);
            DumpResponse.AddTuple(builder, tupleOffset);
            DumpResponse.AddBase(builder, @baseOffset);
            DumpResponse.AddComedia(builder, comedia);
            DumpResponse.AddRtcpMux(builder, rtcp_mux);
            return DumpResponse.EndDumpResponse(builder);
        }

        public static void StartDumpResponse(FlatBufferBuilder builder) { builder.StartTable(6); }
        public static void AddBase(FlatBufferBuilder builder, Offset<FBS.Transport.Dump> baseOffset) { builder.AddOffset(0, baseOffset.Value, 0); }
        public static void AddRtcpMux(FlatBufferBuilder builder, bool rtcpMux) { builder.AddBool(1, rtcpMux, false); }
        public static void AddComedia(FlatBufferBuilder builder, bool comedia) { builder.AddBool(2, comedia, false); }
        public static void AddTuple(FlatBufferBuilder builder, Offset<FBS.Transport.Tuple> tupleOffset) { builder.AddOffset(3, tupleOffset.Value, 0); }
        public static void AddRtcpTuple(FlatBufferBuilder builder, Offset<FBS.Transport.Tuple> rtcpTupleOffset) { builder.AddOffset(4, rtcpTupleOffset.Value, 0); }
        public static void AddSrtpParameters(FlatBufferBuilder builder, Offset<FBS.SrtpParameters.SrtpParameters> srtpParametersOffset) { builder.AddOffset(5, srtpParametersOffset.Value, 0); }
        public static Offset<FBS.PlainTransport.DumpResponse> EndDumpResponse(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // base
            builder.Required(o, 10);  // tuple
            return new Offset<FBS.PlainTransport.DumpResponse>(o);
        }
        public DumpResponseT UnPack()
        {
            var _o = new DumpResponseT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(DumpResponseT _o)
        {
            _o.Base = this.Base.HasValue ? this.Base.Value.UnPack() : null;
            _o.RtcpMux = this.RtcpMux;
            _o.Comedia = this.Comedia;
            _o.Tuple = this.Tuple.HasValue ? this.Tuple.Value.UnPack() : null;
            _o.RtcpTuple = this.RtcpTuple.HasValue ? this.RtcpTuple.Value.UnPack() : null;
            _o.SrtpParameters = this.SrtpParameters.HasValue ? this.SrtpParameters.Value.UnPack() : null;
        }
        public static Offset<FBS.PlainTransport.DumpResponse> Pack(FlatBufferBuilder builder, DumpResponseT _o)
        {
            if(_o == null)
                return default(Offset<FBS.PlainTransport.DumpResponse>);
            var _base = _o.Base == null ? default(Offset<FBS.Transport.Dump>) : FBS.Transport.Dump.Pack(builder, _o.Base);
            var _tuple = _o.Tuple == null ? default(Offset<FBS.Transport.Tuple>) : FBS.Transport.Tuple.Pack(builder, _o.Tuple);
            var _rtcp_tuple = _o.RtcpTuple == null ? default(Offset<FBS.Transport.Tuple>) : FBS.Transport.Tuple.Pack(builder, _o.RtcpTuple);
            var _srtp_parameters = _o.SrtpParameters == null ? default(Offset<FBS.SrtpParameters.SrtpParameters>) : FBS.SrtpParameters.SrtpParameters.Pack(builder, _o.SrtpParameters);
            return CreateDumpResponse(
              builder,
              _base,
              _o.RtcpMux,
              _o.Comedia,
              _tuple,
              _rtcp_tuple,
              _srtp_parameters);
        }
    }
}
