// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;

namespace FBS.PlainTransport
{

    using global::System;
    using global::System.Collections.Generic;
    using global::Google.FlatBuffers;

    public struct GetStatsResponse : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
        public static GetStatsResponse GetRootAsGetStatsResponse(ByteBuffer _bb) { return GetRootAsGetStatsResponse(_bb, new GetStatsResponse()); }
        public static GetStatsResponse GetRootAsGetStatsResponse(ByteBuffer _bb, GetStatsResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public GetStatsResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public FBS.Transport.Stats? Base { get { int o = __p.__offset(4); return o != 0 ? (FBS.Transport.Stats?)(new FBS.Transport.Stats()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public bool RtcpMux { get { int o = __p.__offset(6); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }
        public bool Comedia { get { int o = __p.__offset(8); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }
        public FBS.Transport.Tuple? Tuple { get { int o = __p.__offset(10); return o != 0 ? (FBS.Transport.Tuple?)(new FBS.Transport.Tuple()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public FBS.Transport.Tuple? RtcpTuple { get { int o = __p.__offset(12); return o != 0 ? (FBS.Transport.Tuple?)(new FBS.Transport.Tuple()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<FBS.PlainTransport.GetStatsResponse> CreateGetStatsResponse(FlatBufferBuilder builder,
            Offset<FBS.Transport.Stats> @baseOffset = default(Offset<FBS.Transport.Stats>),
            bool rtcp_mux = false,
            bool comedia = false,
            Offset<FBS.Transport.Tuple> tupleOffset = default(Offset<FBS.Transport.Tuple>),
            Offset<FBS.Transport.Tuple> rtcp_tupleOffset = default(Offset<FBS.Transport.Tuple>))
        {
            builder.StartTable(5);
            GetStatsResponse.AddRtcpTuple(builder, rtcp_tupleOffset);
            GetStatsResponse.AddTuple(builder, tupleOffset);
            GetStatsResponse.AddBase(builder, @baseOffset);
            GetStatsResponse.AddComedia(builder, comedia);
            GetStatsResponse.AddRtcpMux(builder, rtcp_mux);
            return GetStatsResponse.EndGetStatsResponse(builder);
        }

        public static void StartGetStatsResponse(FlatBufferBuilder builder) { builder.StartTable(5); }
        public static void AddBase(FlatBufferBuilder builder, Offset<FBS.Transport.Stats> baseOffset) { builder.AddOffset(0, baseOffset.Value, 0); }
        public static void AddRtcpMux(FlatBufferBuilder builder, bool rtcpMux) { builder.AddBool(1, rtcpMux, false); }
        public static void AddComedia(FlatBufferBuilder builder, bool comedia) { builder.AddBool(2, comedia, false); }
        public static void AddTuple(FlatBufferBuilder builder, Offset<FBS.Transport.Tuple> tupleOffset) { builder.AddOffset(3, tupleOffset.Value, 0); }
        public static void AddRtcpTuple(FlatBufferBuilder builder, Offset<FBS.Transport.Tuple> rtcpTupleOffset) { builder.AddOffset(4, rtcpTupleOffset.Value, 0); }
        public static Offset<FBS.PlainTransport.GetStatsResponse> EndGetStatsResponse(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // base
            builder.Required(o, 10);  // tuple
            return new Offset<FBS.PlainTransport.GetStatsResponse>(o);
        }
        public GetStatsResponseT UnPack()
        {
            var _o = new GetStatsResponseT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(GetStatsResponseT _o)
        {
            _o.Base = this.Base.HasValue ? this.Base.Value.UnPack() : null;
            _o.RtcpMux = this.RtcpMux;
            _o.Comedia = this.Comedia;
            _o.Tuple = this.Tuple.HasValue ? this.Tuple.Value.UnPack() : null;
            _o.RtcpTuple = this.RtcpTuple.HasValue ? this.RtcpTuple.Value.UnPack() : null;
        }
        public static Offset<FBS.PlainTransport.GetStatsResponse> Pack(FlatBufferBuilder builder, GetStatsResponseT _o)
        {
            if(_o == null)
                return default(Offset<FBS.PlainTransport.GetStatsResponse>);
            var _base = _o.Base == null ? default(Offset<FBS.Transport.Stats>) : FBS.Transport.Stats.Pack(builder, _o.Base);
            var _tuple = _o.Tuple == null ? default(Offset<FBS.Transport.Tuple>) : FBS.Transport.Tuple.Pack(builder, _o.Tuple);
            var _rtcp_tuple = _o.RtcpTuple == null ? default(Offset<FBS.Transport.Tuple>) : FBS.Transport.Tuple.Pack(builder, _o.RtcpTuple);
            return CreateGetStatsResponse(
              builder,
              _base,
              _o.RtcpMux,
              _o.Comedia,
              _tuple,
              _rtcp_tuple);
        }
    }

    public class GetStatsResponseT
    {
        public FBS.Transport.StatsT Base { get; set; }

        public bool RtcpMux { get; set; }

        public bool Comedia { get; set; }

        public FBS.Transport.TupleT Tuple { get; set; }

        public FBS.Transport.TupleT RtcpTuple { get; set; }

        public GetStatsResponseT()
        {
            this.Base = null;
            this.RtcpMux = false;
            this.Comedia = false;
            this.Tuple = null;
            this.RtcpTuple = null;
        }
    }


    static public class GetStatsResponseVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyTable(tablePos, 4 /*Base*/, FBS.Transport.StatsVerify.Verify, true)
              && verifier.VerifyField(tablePos, 6 /*RtcpMux*/, 1 /*bool*/, 1, false)
              && verifier.VerifyField(tablePos, 8 /*Comedia*/, 1 /*bool*/, 1, false)
              && verifier.VerifyTable(tablePos, 10 /*Tuple*/, FBS.Transport.TupleVerify.Verify, true)
              && verifier.VerifyTable(tablePos, 12 /*RtcpTuple*/, FBS.Transport.TupleVerify.Verify, false)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
