// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using System.Collections.Generic;
using Google.FlatBuffers;
using System.Text.Json.Serialization;

namespace FBS.WebRtcTransport
{
    public class ListenIndividualT
    {
        public List<FBS.Transport.ListenInfoT> ListenInfos { get; set; }
    }
}
