// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FBS.RtpStream
{
    public enum StatsData : byte
    {
        NONE = 0,

        BaseStats = 1,

        RecvStats = 2,

        SendStats = 3,
    }

    public class StatsDataUnion
    {
        public StatsData Type { get; set; }
        public object Value { get; set; }

        public StatsDataUnion()
        {
            this.Type = StatsData.NONE;
            this.Value = null;
        }

        public T As<T>() where T : class { return this.Value as T; }
        public FBS.RtpStream.BaseStatsT AsBaseStats() { return this.As<FBS.RtpStream.BaseStatsT>(); }
        public static StatsDataUnion FromBaseStats(FBS.RtpStream.BaseStatsT _basestats) { return new StatsDataUnion { Type = StatsData.BaseStats, Value = _basestats }; }
        public FBS.RtpStream.RecvStatsT AsRecvStats() { return this.As<FBS.RtpStream.RecvStatsT>(); }
        public static StatsDataUnion FromRecvStats(FBS.RtpStream.RecvStatsT _recvstats) { return new StatsDataUnion { Type = StatsData.RecvStats, Value = _recvstats }; }
        public FBS.RtpStream.SendStatsT AsSendStats() { return this.As<FBS.RtpStream.SendStatsT>(); }
        public static StatsDataUnion FromSendStats(FBS.RtpStream.SendStatsT _sendstats) { return new StatsDataUnion { Type = StatsData.SendStats, Value = _sendstats }; }

        public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, StatsDataUnion _o)
        {
            switch(_o.Type)
            {
                default:
                    return 0;
                case StatsData.BaseStats:
                    return FBS.RtpStream.BaseStats.Pack(builder, _o.AsBaseStats()).Value;
                case StatsData.RecvStats:
                    return FBS.RtpStream.RecvStats.Pack(builder, _o.AsRecvStats()).Value;
                case StatsData.SendStats:
                    return FBS.RtpStream.SendStats.Pack(builder, _o.AsSendStats()).Value;
            }
        }
    }
}
