// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;

namespace FBS.Message
{

    using global::System;
    using global::System.Collections.Generic;
    using global::Google.FlatBuffers;

    public struct Message : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
        public static Message GetRootAsMessage(ByteBuffer _bb) { return GetRootAsMessage(_bb, new Message()); }
        public static Message GetRootAsMessage(ByteBuffer _bb, Message obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public static bool VerifyMessage(ByteBuffer _bb) { Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, MessageVerify.Verify); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public Message __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public FBS.Message.Body DataType { get { int o = __p.__offset(4); return o != 0 ? (FBS.Message.Body)__p.bb.Get(o + __p.bb_pos) : FBS.Message.Body.NONE; } }
        public TTable? Data<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
        public FBS.Request.Request DataAsRequest() { return Data<FBS.Request.Request>().Value; }
        public FBS.Response.Response DataAsResponse() { return Data<FBS.Response.Response>().Value; }
        public FBS.Notification.Notification DataAsNotification() { return Data<FBS.Notification.Notification>().Value; }
        public FBS.Log.Log DataAsLog() { return Data<FBS.Log.Log>().Value; }

        public static Offset<FBS.Message.Message> CreateMessage(FlatBufferBuilder builder,
            FBS.Message.Body data_type = FBS.Message.Body.NONE,
            int dataOffset = 0)
        {
            builder.StartTable(2);
            Message.AddData(builder, dataOffset);
            Message.AddDataType(builder, data_type);
            return Message.EndMessage(builder);
        }

        public static void StartMessage(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddDataType(FlatBufferBuilder builder, FBS.Message.Body dataType) { builder.AddByte(0, (byte)dataType, 0); }
        public static void AddData(FlatBufferBuilder builder, int dataOffset) { builder.AddOffset(1, dataOffset, 0); }
        public static Offset<FBS.Message.Message> EndMessage(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 6);  // data
            return new Offset<FBS.Message.Message>(o);
        }
        public static void FinishMessageBuffer(FlatBufferBuilder builder, Offset<FBS.Message.Message> offset) { builder.Finish(offset.Value); }
        public static void FinishSizePrefixedMessageBuffer(FlatBufferBuilder builder, Offset<FBS.Message.Message> offset) { builder.FinishSizePrefixed(offset.Value); }
        public MessageT UnPack()
        {
            var _o = new MessageT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(MessageT _o)
        {
            _o.Data = new FBS.Message.BodyUnion();
            _o.Data.Type = this.DataType;
            switch(this.DataType)
            {
                default:
                    break;
                case FBS.Message.Body.Request:
                    _o.Data.Value = this.Data<FBS.Request.Request>().HasValue ? this.Data<FBS.Request.Request>().Value.UnPack() : null;
                    break;
                case FBS.Message.Body.Response:
                    _o.Data.Value = this.Data<FBS.Response.Response>().HasValue ? this.Data<FBS.Response.Response>().Value.UnPack() : null;
                    break;
                case FBS.Message.Body.Notification:
                    _o.Data.Value = this.Data<FBS.Notification.Notification>().HasValue ? this.Data<FBS.Notification.Notification>().Value.UnPack() : null;
                    break;
                case FBS.Message.Body.Log:
                    _o.Data.Value = this.Data<FBS.Log.Log>().HasValue ? this.Data<FBS.Log.Log>().Value.UnPack() : null;
                    break;
            }
        }
        public static Offset<FBS.Message.Message> Pack(FlatBufferBuilder builder, MessageT _o)
        {
            if(_o == null)
                return default(Offset<FBS.Message.Message>);
            var _data_type = _o.Data == null ? FBS.Message.Body.NONE : _o.Data.Type;
            var _data = _o.Data == null ? 0 : FBS.Message.BodyUnion.Pack(builder, _o.Data);
            return CreateMessage(
              builder,
              _data_type,
              _data);
        }
    }

    public class MessageT
    {
        private FBS.Message.Body DataType
        {
            get
            {
                return this.Data != null ? this.Data.Type : FBS.Message.Body.NONE;
            }
            set
            {
                this.Data = new FBS.Message.BodyUnion();
                this.Data.Type = value;
            }
        }

        public FBS.Message.BodyUnion Data { get; set; }

        public MessageT()
        {
            this.Data = null;
        }

        public static MessageT DeserializeFromBinary(byte[] fbBuffer)
        {
            return Message.GetRootAsMessage(new ByteBuffer(fbBuffer)).UnPack();
        }
        public byte[] SerializeToBinary()
        {
            var fbb = new FlatBufferBuilder(0x10000);
            Message.FinishMessageBuffer(fbb, Message.Pack(fbb, this));
            return fbb.DataBuffer.ToSizedArray();
        }
    }


    static public class MessageVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyField(tablePos, 4 /*DataType*/, 1 /*FBS.Message.Body*/, 1, false)
              && verifier.VerifyUnion(tablePos, 4, 6 /*Data*/, FBS.Message.BodyVerify.Verify, true)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
