// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using System.Text.Json.Serialization;
using Google.FlatBuffers;

namespace FBS.AudioLevelObserver
{
    public class VolumeT
    {
        public string ProducerId { get; set; }

        public sbyte Volume_ { get; set; }

        public VolumeT()
        {
            this.ProducerId = null;
            this.Volume_ = 0;
        }
    }
}
