// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;
using Google.FlatBuffers;

namespace FBS.Consumer
{
    public struct SetPriorityRequest : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static SetPriorityRequest GetRootAsSetPriorityRequest(ByteBuffer _bb) { return GetRootAsSetPriorityRequest(_bb, new SetPriorityRequest()); }
        public static SetPriorityRequest GetRootAsSetPriorityRequest(ByteBuffer _bb, SetPriorityRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public SetPriorityRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public byte Priority { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

        public static Offset<FBS.Consumer.SetPriorityRequest> CreateSetPriorityRequest(FlatBufferBuilder builder,
            byte priority = 0)
        {
            builder.StartTable(1);
            SetPriorityRequest.AddPriority(builder, priority);
            return SetPriorityRequest.EndSetPriorityRequest(builder);
        }

        public static void StartSetPriorityRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddPriority(FlatBufferBuilder builder, byte priority) { builder.AddByte(0, priority, 0); }
        public static Offset<FBS.Consumer.SetPriorityRequest> EndSetPriorityRequest(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<FBS.Consumer.SetPriorityRequest>(o);
        }
        public SetPriorityRequestT UnPack()
        {
            var _o = new SetPriorityRequestT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(SetPriorityRequestT _o)
        {
            _o.Priority = this.Priority;
        }
        public static Offset<FBS.Consumer.SetPriorityRequest> Pack(FlatBufferBuilder builder, SetPriorityRequestT _o)
        {
            if(_o == null)
                return default(Offset<FBS.Consumer.SetPriorityRequest>);
            return CreateSetPriorityRequest(
              builder,
              _o.Priority);
        }
    }

    public class SetPriorityRequestT
    {
        [JsonPropertyName("priority")]
        public byte Priority { get; set; }

        public SetPriorityRequestT()
        {
            this.Priority = 0;
        }
    }
}
