// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FBS.Consumer
{

    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    public enum TraceEventType : byte
    {
        [EnumMember(Value = "keyframe")]
        KEYFRAME = 0,

        [EnumMember(Value = "fir")]
        FIR = 1,

        [EnumMember(Value = "nack")]
        NACK = 2,

        [EnumMember(Value = "pli")]
        PLI = 3,

        [EnumMember(Value = "rtp")]
        RTP = 4,
    };


}
