// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;

namespace FBS.Common
{

    using global::System;
    using global::System.Collections.Generic;
    using global::Google.FlatBuffers;

    public struct StringString : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
        public static StringString GetRootAsStringString(ByteBuffer _bb) { return GetRootAsStringString(_bb, new StringString()); }
        public static StringString GetRootAsStringString(ByteBuffer _bb, StringString obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public StringString __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Key { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetKeyBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
        public ArraySegment<byte>? GetKeyBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetKeyArray() { return __p.__vector_as_array<byte>(4); }
        public string Value { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetValueBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
        public ArraySegment<byte>? GetValueBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public byte[] GetValueArray() { return __p.__vector_as_array<byte>(6); }

        public static Offset<FBS.Common.StringString> CreateStringString(FlatBufferBuilder builder,
            StringOffset keyOffset = default(StringOffset),
            StringOffset valueOffset = default(StringOffset))
        {
            builder.StartTable(2);
            StringString.AddValue(builder, valueOffset);
            StringString.AddKey(builder, keyOffset);
            return StringString.EndStringString(builder);
        }

        public static void StartStringString(FlatBufferBuilder builder) { builder.StartTable(2); }
        public static void AddKey(FlatBufferBuilder builder, StringOffset keyOffset) { builder.AddOffset(0, keyOffset.Value, 0); }
        public static void AddValue(FlatBufferBuilder builder, StringOffset valueOffset) { builder.AddOffset(1, valueOffset.Value, 0); }
        public static Offset<FBS.Common.StringString> EndStringString(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // key
            builder.Required(o, 6);  // value
            return new Offset<FBS.Common.StringString>(o);
        }
        public StringStringT UnPack()
        {
            var _o = new StringStringT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(StringStringT _o)
        {
            _o.Key = this.Key;
            _o.Value = this.Value;
        }
        public static Offset<FBS.Common.StringString> Pack(FlatBufferBuilder builder, StringStringT _o)
        {
            if(_o == null)
                return default(Offset<FBS.Common.StringString>);
            var _key = _o.Key == null ? default(StringOffset) : builder.CreateString(_o.Key);
            var _value = _o.Value == null ? default(StringOffset) : builder.CreateString(_o.Value);
            return CreateStringString(
              builder,
              _key,
              _value);
        }
    }

    public class StringStringT
    {
        public string Key { get; set; }

        public string Value { get; set; }

        public StringStringT()
        {
            this.Key = null;
            this.Value = null;
        }
    }


    static public class StringStringVerify
    {
        static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
        {
            return verifier.VerifyTableStart(tablePos)
              && verifier.VerifyString(tablePos, 4 /*Key*/, true)
              && verifier.VerifyString(tablePos, 6 /*Value*/, true)
              && verifier.VerifyTableEnd(tablePos);
        }
    }

}
